---
name: Ansible Galaxy

on:
  create:
    tags:

jobs:
  import:
    name: Import role
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: 0x022b/galaxy-role-import-action@v1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
